version: '3'
services:
  prep:
    image: 'iconloop/prep-node:1911121115x323d60'
    container_name: "prep"
    restart: "always"
    environment:
        LOOPCHAIN_LOG_LEVEL: "SPAM"
        ICON_LOG_LEVEL: "DEBUG"
        DEFAULT_PATH: "/data/loopchain"
        LOG_OUTPUT_TYPE: "file|console"
        FASTEST_START: "yes"
        CERT_PATH: "/cert"
        PRIVATE_KEY_FILENAME: "key"
        PRIVATE_PASSWORD: "qqaa1122!"
    cap_add:
        - SYS_TIME
    volumes:
        - ./data:/data
        - ./cert:/cert:ro
    networks:
        - prep-net

  nginx_throttle:
    image: looploy/nginx:1.17.1
    container_name: nginx_1.17
    environment:
        NGINX_LOG_OUTPUT: 'file'
        NGINX_LOG_TYPE: 'main'
        NGINX_USER: 'root'
        VIEW_CONFIG: "yes"
        USE_NGINX_THROTTLE: "yes" ## throthle use = yes change
        NGINX_THROTTLE_BY_IP_VAR: "$$binary_remote_addr"
        NGINX_THROTTLE_BY_URI: "yes"
        NGINX_THROTTLE_BY_IP: "yes"
        NGINX_RATE_LIMIT: "100r/s"
        NGINX_BURST: "5"
        NGINX_SET_NODELAY: "no"
        USE_NGINX_STATUS: "yes"
        NGINX_STATUS_URI: "nginx_status"
        NGINX_STATUS_URI_ALLOWIP: "127.0.0.1"
        GRPC_PROXY_MODE: "yes"
        USE_VTS_STATUS: "yes"
        TZ: "GMT-9"
        SET_REAL_IP_FROM: "0.0.0.0/0"
        PREP_MODE: "yes"
        NODE_CONTAINER_NAME: "prep"
        PREP_NGINX_ALLOWIP: "no"  ## whiltlist user = yes change
        NGINX_ALLOW_IP: "0.0.0.0/0"
        NGINX_LOG_FORMAT: '$$realip_remote_addr $$remote_addr  $$remote_user [$$time_local] $$request $$status $$body_bytes_sent $$http_referer "$$http_user_agent" $$http_x_forwarded_for $$http_x_real_ip $$request_body $$server_protocol'
    volumes:
        - ./data/loopchain/nginx:/var/log/nginx
        - ./user_conf:/etc/nginx/user_conf
    ports:
        - '7100:7100'
        - '9000:9000'
        - '8080:8080'
    networks:
        - prep-net


  loop-logger:
    image: looploy/fluentd:20191029
    container_name: loop-logger
    restart: always
    # network_mode: host
    volumes:
        - ./data/loopchain:/loopchain
        - ./fluent/log:/fluentd/log
    environment:
      LOG_SERVER_IP: loop-logger-server
    ports:
        - '24224:24224'
        # - '5140:5140/udp'
    networks:
      - prep-net
    
  loop-logger-server:
    image: looploy/fluentd:20191029
    container_name: loop-logger-server
    restart: always
    # network_mode: host
    volumes:
        - ./fluent/log:/fluentd/log
    environment:
        FLUENTD_MODE: server
        FLUENTD_MATCH_ELA_HOST: elasticsearch
    ports:
    # - '24224:24224'
    - '5140:5140/udp'
    networks:
      - prep-net

  elasticsearch:
    image: elasticsearch:7.4.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - prep-net

  kibana:
    image: kibana:7.4.1
    environment:
      container_name: kibana
    ports:
      - '5601:5601'
    networks:
      - prep-net 

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '13000:3000'
    networks:
      - prep-net
networks:
  prep-net:
